version: '3.8'
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lostfound
    ports:
      - "5432:5432"

  ml_service:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    working_dir: /app
    volumes:
      - ./ml_service:/app
    ports:
      - "8000:80"
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
