#version: '3.8'

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    expose:
      - "4173"  # internal only
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

    command: npm run dev -- --host --port 4173

  ml_service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./ml_service:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    runtime: nvidia

  nginx:
    image: nginx:alpine
    ports:
      - "5173:443"  # external port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend

volumes:
  db_data:
